export const blackBackgroundNominees = [
  "bacchus",
  "bambi",
  "18&10 apero club",
  "bambolo",
  "l'ile",
  "ile",
  "les assembleurs",
  "assembleurs",
  "petit bleu",
  "le petit bleu",
  "plouf",
  "bistrot des celestins",
  "bdc",
  "tilt",
  "loft club",
  "avenue 45",
  "l'avenue 45",
  "drungly",
  "club la maison",
  "le club",
  "le club by la maison",
  "club by la maison",
  "rambler",
  "rambler cocktail club",
  "quai 22",
  "six",
  "le six",
  "horloge",
  "l'horloge",
  "antonin",
  "maison bleue",
  "la maison bleue",
  "feria",
  "la feria",
  "cigale",
  "la cigale",
  "val dc",
  "tom gio",
  "ily"
];