export const blackBackgroundNominees = [
  "bus paradise",
  "BUS PARADISE",
  "Bus Paradise",
  "kaia",
  "KAIA",
  "Kaia",
  "nel's club",
  "NEL'S CLUB",
  "Nel's Club",
  "la maison bleue",
  "LA MAISON BLEUE",
  "La Maison Bleue",
  "la feria",
  "LA FERIA",
  "La Feria",
  "mademoiselle simone",
  "MADEMOISELLE SIMONE",
  "Mademoiselle Simone",
  "you",
  "YOU",
  "You",
  "la cigale",
  "LA CIGALE",
  "La Cigale",
  "au bon secours",
  "AU BON SECOURS",
  "Au Bon Secours",
  "casa jaguar",
  "CASA JAGUAR",
  "Casa Jaguar",
  "poisson chat",
  "POISSON CHAT",
  "Poisson Chat",
  "lockers",
  "LOCKERS",
  "Lockers",
  "javoo",
  "JAVOO",
  "Javoo",
  "bar by la maison",
  "BAR BY LA MAISON",
  "Bar by La Maison",
  "le bar by la maison",
  "LE BAR BY LA MAISON",
  "Le Bar by La Maison",
  "my",
  "MY",
  "My",
  "bambi",
  "BAMBI",
  "Bambi",
  "plan b",
  "PLAN B",
  "Plan B",
  "le plan b",
  "LE PLAN B",
  "Le Plan B",
  "the maze",
  "THE MAZE",
  "The Maze",
  "f&k",
  "F&K",
  "F&k",
  "f&K",
  "f&k bistro club",
  "F&K BISTRO CLUB",
  "F&K Bistro Club",
  "bacchus",
  "BACCHUS",
  "Bacchus",
  "bacchus plaza",
  "BACCHUS PLAZA",
  "Bacchus Plaza",
  "l'ile",
  "L'ILE",
  "L'Ile",
  "l'ile restaurant",
  "L'ILE RESTAURANT",
  "L'Ile Restaurant",
  "18&10",
  "18&10 APERO CLUB",
  "18&10 Apero Club",
  "glam club",
  "GLAM CLUB",
  "Glam Club",
  "klub",
  "KLUB",
  "Klub",
  "club 400",
  "CLUB 400",
  "Club 400",
  "justin",
  "JUSTIN",
  "Justin",
  "biniou",
  "BINIOU",
  "Biniou",
  "faute aux ours",
  "FAUTE AUX OURS",
  "Faute aux Ours",
  "fao",
  "FAO",
  "Fao",
  "espit chupitos",
  "ESPIT CHUPITOS",
  "Espit Chupitos",
  "l'excuse",
  "L'EXCUSE",
  "L'Excuse",
  "lexcuse",
  "LEXCUSE",
  "Lexcuse"
];
